package net.hedtech.banner.general.communication.letter.pdf

import net.hedtech.banner.testing.BaseIntegrationTestCase
import org.junit.After
import org.junit.Before
import org.junit.Test
import org.springframework.security.authentication.UsernamePasswordAuthenticationToken
import org.springframework.security.core.context.SecurityContextHolder

/**
 * Tests converting html to pdf.
 */
class CommunicationHtmlToPdfConverterIntegrationTests extends BaseIntegrationTestCase {

    def selfServiceBannerAuthenticationProvider


    @Before
    public void setUp() {
        formContext = ['SELFSERVICE']
        def authentication = selfServiceBannerAuthenticationProvider.authenticate( new UsernamePasswordAuthenticationToken( 'BCMADMIN', '111111' ) )
        SecurityContextHolder.getContext().setAuthentication( authentication )
        super.setUp()
    }


    @After
    public void tearDown() {
        super.tearDown()
        logout()
    }

    @Test
    void simpleTest() {
        String htmlContent =
"""<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
    <head>
        <title>
                Generated By Ellucian Communication Management
        </title>
        <style type="text/css">
        @page { size: A4;  margin-top: 1in; margin-bottom: 1in; margin-left: 1in; margin-right: 1in; }
        </style>
    </head>
    <body>
        <h1>My First Heading</h1>
        <p>My first paragraph.</p>
        This is a test.
    </body>
</html>
"""
        CommunicationHtmlToPdfConverter converter = new CommunicationHtmlToPdfConverter()
        converter.writeHtml( htmlContent )
        converter.finish()
        byte[] pdfContent = converter.toPdf()

        assertNotNull( pdfContent )
        assertTrue( new String( pdfContent ).startsWith( "%PDF" ) )
    }

}
